spring.application.name=is-technical-test

server.servlet.context-path=/api

# MongoDB
spring.data.mongodb.auto-index-creation=true

app.scheduler.pool-size=4

# Poitiers
app.scheduler.tasks.POITIERS_PARKING.enabled=true
# Every minute
app.scheduler.tasks.POITIERS_PARKING.cron=0 * * * * *
app.scheduler.tasks.POITIERS_PARKING.url=https://data.grandpoitiers.fr/data-fair/api/v1/datasets/mobilites-stationnement-des-parkings-en-temps-reel/lines

# Another partner/city.
# app.scheduler.tasks.<partner/city>.enabled=false
# app.scheduler.tasks.<partner/city>.cron=0 * * * * *
# app.scheduler.tasks.<partner/city>.url=<URL>
